<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1006898" started-at="2015-10-28T19:31:50Z" finished-at="2015-10-28T19:48:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1006898" started-at="2015-10-28T19:31:50Z" finished-at="2015-10-28T19:48:37Z">
      <class name="com.balfour.sb4.unittests.genericTest001">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.balfour.sb4.unittests.genericTest001@10bdf5e5]" name="setup" is-config="true" duration-ms="9644" started-at="2015-10-28T14:31:40Z" finished-at="2015-10-28T14:31:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="testSetUp()[pri:0, instance:com.balfour.sb4.unittests.genericTest001@10bdf5e5]" name="testSetUp" is-config="true" duration-ms="6081" started-at="2015-10-28T14:31:50Z" finished-at="2015-10-28T14:31:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetUp -->
        <test-method status="FAIL" signature="ocoTest003()[pri:0, instance:com.balfour.sb4.unittests.genericTest001@10bdf5e5]" name="ocoTest003" duration-ms="1000809" started-at="2015-10-28T14:31:56Z" finished-at="2015-10-28T14:48:37Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[OCO Info did not match]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: OCO Info did not match
	at com.balfour.sb4.unittests.genericTest001.ocoTest003(genericTest001.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ocoTest003 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.balfour.sb4.unittests.genericTest001@10bdf5e5]" name="teardown" is-config="true" duration-ms="129" started-at="2015-10-28T14:48:37Z" finished-at="2015-10-28T14:48:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.balfour.sb4.unittests.genericTest001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
